language: python

install:

  - pip install -r requirements.txt

script:

  - pytest
  - coverage run -m pytest # tell Travis CI to do coverage analysis

after_success:
  - bash <(curl -s https://codecov.io/bash) # send coverage results to codecov
